
/* Automatically generated by './webpack/watcher.js' */

import Button from './components/button/index.js';
import Huazi from './components/huazi/index.js';

const components = [
  Button,
  Huazi,
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });

  // Vue.use(InfiniteScroll);

  Vue.prototype.$zui = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

  // Vue.prototype.$loading = Loading.service;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
  Button,
  Huazi
};
